#  ------------------------------
# |    SchematicUpload Config    |
# |    Developed by William278   |
#  ------------------------------

language: 'en-gb'
custom_schematic_directory: ''
web_server:
  port: 2780
  url: ''
upload_limits:
  max_schematic_file_size: 2
  period_minutes: 60
  schematics_per_period: 3