name: SchematicUpload
version: '${version}'
main: net.william278.schematicupload.SchematicUpload
api-version: 1.16
description: Plugin that provides a web server interface for uploading WorldEdit schematics
commands:
  uploadschematic:
    usage: /uploadschematic
    description: Upload a schematic
    aliases: [uploadschem, upschem, uschem]